export const Routes = {
  SPLASH_SCREEN: "SPLASH_SCREEN",
  SETUP_SCREEN: "SETUP_SCREEN",
  HOME_SCREEN: "HOME_SCREEN",
  IDEAS_SCREEN: "IDEAS_SCREEN",
  INVITE_SCREEN: "INVITE_SCREEN",
  PAYMENT_SCREEN: "PAYMENT_SCREEN",
  DETAILS_SCREEN: "DETAILS_SCREEN",
  TERMS_OF_SERVICES_SCREEN: "TERMS_OF_SERVICES_SCREEN",
  PRIVACY_POLICY_SCREEN: "PRIVACY_POLICY_SCREEN",
  MAIN_SCREEN: "MAIN_SCREEN",
};
