export const Routes = {
  SETUP_SCREEN: "SETUP_SCREEN",
  HOME_SCREEN: "HOME_SCREEN",
  IDEAS_SCREEN: "IDEAS_SCREEN",
  INVITE_SCREEN: "INVITE_SCREEN",
  PAYMENT_SCREEN: "PAYMENT_SCREEN",
  DETAILS_SCREEN: "DETAILS_SCREEN",
};
